### ISSUE TITLE
Should there be a "stroke-current" to change the stroke color?

### ISSUE THREAD

**Issue by mstum** [StackExchange/Stacks#155]
**Is your feature request related to a problem? Please describe.**
I have an SVG File that has a path defined as a stroke, not just a fill and I want to color it.

**Describe the solution you'd like**
```css
/* Or add to fill-current */
.stroke-current {
  stroke: currentColor !important;
}
```

**Describe alternatives you've considered**
I could figure out how to convert the path to one that uses a fill instead of a stroke.

**Additional context**
The Path in question:

`<path stroke-width=".265" d="M0 19.174h94.485" />`
