### ISSUE TITLE
Add a class for user-select: none

### ISSUE THREAD

**Issue by mstum** [StackExchange/Stacks#251]
**Is your feature request related to a problem? Please describe.**
For some elements (e.g., spans or a tags that look like buttons), being able to select the text is undesireable. Pointer-Events: none disables any and all interaction.

**Describe the solution you'd like**
```css
.disable-select {
  -webkit-user-select: none;  
  -moz-user-select: none;    
  -ms-user-select: none;      
  user-select: none;
}
```

**Describe alternatives you've considered**
Using a style tag, or living with the fact that the user can select it.
