### ISSUE TITLE
Notices should respond to different viewports

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#69]
Our toast notifications don't appear centered horizontally at smaller viewports.

**Comment by bnickel** [comment]
There are a couple problems:

1. The toast isn't actually centered.  It's left is at `50% - 16rem` and its right is at `50% + 26rem`.  I'm assuming this is a correction made for the left sidebar, but the left sidebar isn't always there.  Not knowing enough about the Stacks design philosophy, I'd say it should be truly centered with `margin-left: -21rem` and then consuming sites should override its `left` rule in cases when left/right nav affects the available space.  For SO, that would look something like:

    ```less
    IF_LEFT_NAV_VISIBLE {
        .s-notice__toast {
            left: calc(50% +82px);
        }
    }
    ```

2. We aren't responsive.  I would just say if viewport width < 44rem, unset width and left-margin, and instead pin right and left to an appropriate distance from the screen edge.
